---

- name: Create script
  template:
    src: interfaces_config.sh
    dest: "/root/scripts/interfaces_config.sh"
    mode: 0755

- name: Create script
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/interfaces_config.service"
    mode: 0644

- name: Enable service interfaces_config
  systemd:
    name: interfaces_config
    daemon_reload: yes
    enabled: yes
